version: '3.6'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    hostname: django
    image: djpkg-dev-django
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    ports:
      - "18000:8000"
    volumes:
      - .:/app
      - djpkg_static_dev:/data/static
      - djpkg_media_dev:/data/media

  postgres:
    build: ./compose/postgres
    hostname: postgres
    image: djpkg-dev-postgres
    env_file:
      - .env.local
    ports:
      - "45432:5432"
    volumes:
      - djpkg_postgres_data_dev:/var/lib/postgresql/data
      - djpkg_postgres_backup_dev:/backups
    healthcheck:
      test: [
          "CMD",
          "/usr/local/bin/healthcheck_pg.sh",
      ]
      interval: 3s
      timeout: 3s
      retries: 30

  redis:
    build: ./compose/redis
    hostname: redis
    image: djpkg-dev-redis
    healthcheck:
      test: [
          "CMD",
          "redis-cli",
          "ping"
      ]
      interval: 3s
      timeout: 3s
      retries: 30

volumes:
  djpkg_postgres_data_dev: {}
  djpkg_postgres_backup_dev: {}
  djpkg_media_dev: {}
  djpkg_static_dev: {}
